// <auto-generated />
namespace BlazingShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingimagecolumntoproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingimagecolumntoproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202009140233068_adding image column to product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
